/** Telemetría normalizada completa (salida de DataNormalizer, equivalente V3). */
export interface TelemetryData {
  Speed: number;
  SpeedDisplay: number;
  SpeedUnit: 'MPH' | 'km/h';
  ProjectedSpeed: number;
  Acceleration: number;
  GForce: number;
  LateralG: number;
  SpeedLimit: number;
  TrackLimit: number;
  SignalLimit: number;
  FrontalSpeedLimit: number;
  Gradient: number;
  RawGradient: number;
  DistToNextSignal: number;
  NextSignalAspect: string;
  NextSpeedLimit: number;
  DistToNextSpeedLimit: number;
  NextLimit2Speed: number;
  DistToNextLimit2: number;
  UpcomingLimits: { speed: number; distance: number }[];
  StationDistance: number;
  StationAnchorM?: number;
  StationTraveledM?: number;
  StationDriftM?: number;
  StationNearCorrected?: number;
  StationName: string;
  StationLength: number;
  StationNameOCR: string;
  StationETA: string;
  StationScheduled: string;
  Throttle: number;
  TrainBrake: number;
  CombinedControl: number;
  Reverser: number;
  BrakeCylinderPressure: number;
  BrakePipePressure: number;
  MainResPressure: number;
  EqResPressure: number;
  PressureUnit: 'BAR' | 'PSI';
  Amperage: number;
  AmperageUnit: string;
  Ammeter: number;
  TractiveEffort: number;
  TractionPercent: number;
  BrakingEffort: number;
  BrakingPercent: number;
  TrainLength: number;
  TrainMass: number;
  ConsistType: number;
  TrainType: number;
  ActiveCab: number;
  ProjectedBrakingDistance: number;
  TripDistance: number;
  TailDistanceRemaining: number;
  TailSecondsRemaining: number;
  TailIsActive: boolean;
  LocoName: string;
  RVNumber: string;
  RouteID: string;
  ScenarioPath: string;
  X: number;
  Z: number;
  location: string;
  IsEmergency: boolean;
  Timestamp: number;
  AWS: number;
  AWSState: number;
  AWSReset: number;
  AWSWarning: number;
  AWSWarnCount: number;
  DSD: number;
  VigilAlarm: number;
  Vigilance: number;
  DVDAlarm: number;
  DRA: boolean;
  Sander: boolean;
  DoorsOpen: { left: boolean; right: boolean };
  TimeOfDay: string;
}

export const DEFAULT_TELEMETRY_DATA: TelemetryData = {
  Speed: 0,
  SpeedDisplay: 0,
  SpeedUnit: 'MPH',
  ProjectedSpeed: 0,
  Acceleration: 0,
  GForce: 0,
  LateralG: 0,
  SpeedLimit: 0,
  TrackLimit: 0,
  SignalLimit: 0,
  FrontalSpeedLimit: 0,
  Gradient: 0,
  RawGradient: 0,
  DistToNextSignal: 0,
  NextSignalAspect: 'CLEAR',
  NextSpeedLimit: 0,
  DistToNextSpeedLimit: 0,
  NextLimit2Speed: 0,
  DistToNextLimit2: 0,
  UpcomingLimits: [],
  StationDistance: -1,
  StationName: '',
  StationLength: 200,
  StationNameOCR: '',
  StationETA: '',
  StationScheduled: '',
  Throttle: 0,
  CombinedControl: 0,
  TrainBrake: 0,
  Reverser: 0,
  BrakeCylinderPressure: 0,
  BrakePipePressure: 0,
  MainResPressure: 0,
  EqResPressure: 0,
  PressureUnit: 'BAR',
  Amperage: 0,
  AmperageUnit: 'A',
  Ammeter: 0,
  TractiveEffort: 0,
  TractionPercent: 0,
  BrakingEffort: 0,
  BrakingPercent: 0,
  TripDistance: 0,
  TrainLength: 0,
  TrainMass: 0,
  ConsistType: 0,
  TrainType: 1,
  ActiveCab: 1,
  ProjectedBrakingDistance: 0,
  TailDistanceRemaining: 0,
  TailSecondsRemaining: 0,
  TailIsActive: false,
  LocoName: 'DETECTING...',
  RVNumber: '',
  RouteID: '',
  ScenarioPath: '',
  X: 0,
  Z: 0,
  location: 'UNKNOWN',
  IsEmergency: false,
  Timestamp: 0,
  AWS: 0,
  AWSState: 0,
  AWSReset: 0,
  AWSWarning: 0,
  AWSWarnCount: 0,
  DSD: 0,
  VigilAlarm: 0,
  Vigilance: 0,
  DVDAlarm: 0,
  DRA: false,
  Sander: false,
  DoorsOpen: { left: false, right: false },
  TimeOfDay: '00:00:00',
};
