-- Place this file in your railworks plugins folder
-- Usually C:\Program Files (x86)\Steam\steamapps\common\railworks\plugins (for 64 bit windows)
-- or C:\Program Files\Steam\steamapps\common\railworks\plugins (for 32 bit windows)

--The command used to check if a certain control exists or not and if it does
-- retreive its value is:-

-- if Call("*:ControlExists", Name of control, 0) == 1 then
-- variable = Call( "*:GetControlValue", Name of control, 0 )
--end

--This code block as you will see is used throughout the script to retrieve
--the data for each control required and can easily be added to or deleted from.
--I have included in the files 'Railworks EngineData.pdf' which lists all the
--control names I have found along with their min/max/default values.
--I then use the local variable data to store the name of the control followed by a colon
-- and the return value and a new line. The data variable is added to as each control is read
-- throughout the script and at the end of the script we open the plugins/GetData.txt file
-- and write the whole data variable to the file ready for reading into your program.

--A word of warning, be careful with your syntax when editing lua script files because
--the only way you know something is wrong is when the script does not work. That is
--why I have included the line gCurrentTime = Call( "*:GetSimulationTime", 0 ). If your
--script is OK then the line at the end of the textbox display in my C# program will
--display "Current Time = :" followed by the time in seconds counting up. If this line
--is static then there is an error in your script. So my advice is make small changes
--and test your script regularly. 

-------------------  GetData function --------------------
gData = ""
delay = 5 
counter = 3 --Loop counter to only update every number of itterations set bt delay variable
dataread = 0
previousValues = {}
speedoType = 0 -- 0 = none, 1 = MPH, 2 = KPH
MPH = 2.23693629 -- 2.23694 --Convert meters per second to MPH
KPH = 3.60	--Convert meters per second to KPH
delete_Files = 1 --We need to delete the Getdata.txt and sendcommand.txt files on first run so updated data is received
function getdata ()
--If this is the first run then delete the getdata.txt and sendcommand.txt files
	if delete_Files == 1 then
		deleteFiles() --Delete old data first.
	end
	counter = counter + 1
	if counter >= delay then
		if Call ("GetIsEngineWithKey") == 1 then --Check we are driving the train.
			gData = ""
			local speedMPS = Call("GetSpeed", 0) or 0
			local simTime = Call("GetSimulationTime", 0) or 0
			local grad = Call("GetGradient", 0) or 0
			gData = string.format("Speed:%.2f|SimulationTime:%.2f|Gradient:%.2f", speedMPS * MPH, simTime, grad)

			GetSpeedInfo()
			GetControlData () -- Extract data for controls only.
			GetSpeedLimits () -- Get current & next speed limits as well as distance to next speed limit.
			WriteData () -- Write the data extracted by GetControlData() to GetData.txt.
			SendData () -- Reads 'SendCommand.txt' file generated by 'TS2015 Raildriver Interface.exe' & passes data back to TS2015.
		end
		counter = 0
		gData = ""
	end
end

function GetSpeedInfo()
		local ControlType = "Speed"
	local ControlName = ""
	local ControlMin = 0
	local ControlMax = 0
	local ControlValue = 0
	
	if Call("ControlExists", "SpeedometerMPH", 0) == 1 then
		speedoType = 1
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = Call("GetControlMaximum", "SpeedometerMPH", 0)
		ControlValue = 1 -- MPH
		gData = gData .. "|" .. ControlName .. ":" .. ControlValue .. "|MaxSpeed:" .. ControlMax
	elseif Call("ControlExists", "MySpeedometerMPH", 0) == 1 then
		speedoType = 1
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = Call("GetControlMaximum", "MySpeedometerMPH", 0)
		ControlValue = 1 -- MPH
		gData = gData .. "|" .. ControlName .. ":" .. ControlValue .. "|MaxSpeed:" .. ControlMax
	elseif Call("ControlExists", "SpeedometerKPH", 0) == 1 then
		speedoType = 2
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = Call("GetControlMaximum", "SpeedometerKPH", 0)
		ControlValue = 2 -- KPH
		gData = gData .. "|" .. ControlName .. ":" .. ControlValue .. "|MaxSpeed:" .. ControlMax
	elseif Call("ControlExists", "MySpeedometerKPH", 0) == 1 then
		speedoType = 2
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = Call("GetControlMaximum", "MySpeedometerKPH", 0)
		ControlValue = 2 -- KPH
		gData = gData .. "|" .. ControlName .. ":" .. ControlValue .. "|MaxSpeed:" .. ControlMax
	else
		speedoType = 0
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 0
		ControlValue = 0 -- No Speedo Fitted
		gData = gData .. "|" .. ControlName .. ":" .. ControlValue .. "|MaxSpeed:250"
	end

	ControlName = "CurrentSpeed"
	ControlMin = 0
	--ControlMax = 3000
	ControlValue = Call("GetSpeed")
	
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- gData ya actualizado
end

function GetControlData()
	local ControlName = ""
	local ControlValue = 0
	
	ControlName = "TimeOfDay"
	ControlValue = SysCall("ScenarioManager:GetTimeOfDay")
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	
	ControlName = "Acceleration"
	ControlValue = Call("GetAcceleration")
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	
	ControlName = "Gradient"
	ControlValue = Call("GetGradient")
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	
	-- Información del Consist (Longitud y Masa)
	ControlName = "TrainLength"
	ControlValue = Call("GetConsistLength")
	gData = gData .. "|" .. ControlName .. ":" .. string.format("%.2f", ControlValue)

	ControlName = "TrainMass"
	ControlValue = Call("GetConsistTotalMass") / 1000 -- Convertir Kg a Toneladas
	gData = gData .. "|" .. ControlName .. ":" .. string.format("%.2f", ControlValue)
	
	-- Captura Extendida de Controles para Dashboard Nexus v3.1 (Solo Modernos/Expert)
	local controlsToRead = {
		-- Tracción y Dinámica
		"Ammeter", "Effort", "TractiveEffort", "Regulator", "Reverser", "DynamicBrake",
		"SpeedometerMPH", "SpeedometerKPH",
		
		-- Sistemas de Freno (Presiones en BAR)
		"TrainBrakeCylinderPressureBAR", "TrainBrakePipePressureBAR", 
		"MainResPressureBAR", "EngineBrakeCylinderPressureBAR", "EqResPressureBAR",
		
		-- Mandos de Freno
		"TrainBrakeControl", "EngineBrakeControl", "DynamicBrakeControl", "HandBrake",
		
		-- Sistemas de Seguridad y Señalización
		"AWS", "AWSReset", "AWSWarning", "AWSWarnCount", "AWSWarnAudio", "VigilAlarm", "Vigilance", "DSD", "DVDAlarm", "DVDPedal", "TPWS", "EmergencyBrake", "DRA",
		"PZB_90", "PZB_Befehl40", "PZB_Frei", "PZB_Wachsam", "LZB_Fahrt", "LZB_H",
		
		-- Auxiliares y Cabina
		"Sander", "Pantograph", "DoorsOpenClose", "DoorsOpenCloseLeft", "DoorsOpenCloseRight",
		"Headlights", "CabLights", "Wipers", "WiperSpeed", "Horn", "Bell",
		"FuelLevel", "Gear", "MasterKey"
	}

	for _, name in ipairs(controlsToRead) do
		if Call("ControlExists", name, 0) == 1 then
			local val = Call("GetControlValue", name, 0)
			gData = gData .. "|" .. name .. ":" .. string.format("%.2f", val)
		end
	end
end

function GetSpeedLimits ()
		local ControlType = "SpeedLimit"
	local ControlName = ""
	local ControlMin = 0
	local ControlMax = 0
	local ControlValue = ""
	
	ControlValue = Call( "GetCurrentSpeedLimit" )
	if (speedoType <= 1) then
		ControlValue = string.format("%1.1f", ControlValue * MPH)
	elseif (speedoType == 2) then 
		ControlValue = string.format("%1.1f", ControlValue * KPH)
	end
	ControlName = "CurrentSpeedLimit"
	ControlMin = 0
	ControlMax = 300
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue

	NextSpeedLimitType, NextSpeedLimitSpeed, NextSpeedLimitDistance = Call("GetNextSpeedLimit", 0)

	ControlValue = NextSpeedLimitType
	ControlName = "NextSpeedLimitType"
	ControlMin = 0
	ControlMax = 10
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- currentvalues[ControlName] = ControlValue

	ControlValue = NextSpeedLimitSpeed
	ControlName = "NextSpeedLimitSpeed"
	ControlMin = 0
	ControlMax = 500
	-- Check speedlimit does not exceed 1000 as some tracks report no speed limit as very high value
	-- 1225016488463523100000000000000000000000.0 which crashes the C# program
	if (ControlValue >= 1000) then 
		ControlValue = string.format("%1.1f", 0)
	end
	
	if (speedoType <= 1 ) then 
		ControlValue = string.format("%1.1f", ControlValue * MPH)
	elseif (speedoType == 2) then 
		ControlValue = string.format("%1.1f", ControlValue * KPH)
	end
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- currentvalues[ControlName] = ControlValue

	ControlValue = string.format("%d", NextSpeedLimitDistance)
	ControlName = "NextSpeedLimitDistance"
	ControlMin = 0
	ControlMax = 10000
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- currentvalues[ControlName] = ControlValue
	
	NextSpeedLimitBackType, NextSpeedLimitBackSpeed, NextSpeedLimitBackDistance = Call("GetNextSpeedLimit", 1)

	ControlValue = NextSpeedLimitBackType
	ControlName = "NextSpeedLimitBackType"
	ControlMin = 0
	ControlMax = 10
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- currentvalues[ControlName] = ControlValue

	ControlValue = NextSpeedLimitBackSpeed
	ControlName = "NextSpeedLimitBackSpeed"
	ControlMin = 0
	ControlMax = 500
	-- Check speedlimit does not exceed 1000 as some tracks report no speed limit as very high value
	-- 1225016488463523100000000000000000000000.0 which crashes the C# program
	if (ControlValue >= 1000) then 
		ControlValue = string.format("%1.1f", 0)
	end
	
	if (speedoType <= 1 ) then 
		ControlValue = string.format("%1.1f", ControlValue * MPH)
	elseif (speedoType == 2) then 
		ControlValue = string.format("%1.1f", ControlValue * KPH)
	end
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- currentvalues[ControlName] = ControlValue

	ControlValue = string.format("%d", NextSpeedLimitBackDistance)
	ControlName = "NextSpeedLimitBackDistance"
	ControlMin = 0
	ControlMax = 10000
	gData = gData .. "|" .. ControlName .. ":" .. ControlValue
	-- gData ya actualizado
				
end
	
function WriteData()
	local file = io.open("plugins/GetData.txt", "w")
	if file then
		file:write(gData)
		file:close()
	end
end

function SendData ()

	-- Read file & send data to Railworks
	--1st we read a line from the SendCommand.txt file
	for line in io.lines("plugins/SendCommand.txt") do 
		--Check to make sure it isn't a blank line
		if line ~= "" then
			--it isn't blank so create a table(array) to hold the variables
			t = {}
			i = 1
			--Look for the colon(:) in the file that separates the control name
			-- from the value to send
			for str in string.gfind(line, "[^:]+") do
				--Place the control name in t[1] then increment i
				--and place the value for the control in t[2]
				t[i] = str
				i = i + 1
			end
			
			--Force controls to 0 on first run
			if dataread == 0 then
				previousValues[t[1]] = -1
				t[2] = 0
			end

			if t[1]~= "Wipers" and t[1] ~= "WiperSpeed" and t[1] ~= "swDriverWiper" then
				if previousValues[t[1]] ~= t[2] then
					--Send the command to railworks. The format is:-
					--Call("*:SetControlValue", Control name, 0 (for lead engine), value for the control)
					if OnControlValueChange then
						OnControlValueChange(t[1], 0, tonumber(t[2]))
					else
						Call( "SetControlValue", t[1], 0, tonumber(t[2])) 
					end
					Call("SetControlTargetValue", t[1], 0, tonumber(t[2]))
					previousValues[t[1]] = t[2]
				end
			end
			
			if t[1] == "Wipers" or t[1] == "WiperSpeed" or t[1] == "swDriverWiper" then
				if previousValues[t[1]] ~= 0 or previousValues[t[1]] ~= t[2] then 
					--Send the command to railworks. The format is:-
					--Call("SetControlValue", Control name, 0 (for lead engine), value for the control)
					if OnControlValueChange then
						OnControlValueChange(t[1], 0, tonumber(t[2]))
					else
						Call( "SetControlValue", t[1], 0, tonumber(t[2])) 
					end
					Call("SetControlTargetValue", t[1], 0, tonumber(t[2]))
				end
				previousValues[t[1]] = t[2]
			end
		end
	end
	dataread = 1
end

function deleteFiles()
	os.remove("plugins/GetData.txt")
	os.remove("plugins/SendCommand.txt")
	delete_Files = 0
end

function Update(time)
	getdata()
end
